### DISCUSSION TITLE
Battery SOH

### DISCUSSION THREAD

**Discussion by martynhr** [flobz/psa_car_controller#690] [Q&A]
Hi,  Is there anyway to get Battery SOH into Home Assistant?
I can see it in the 'Control' tab but I don't know the url nor can I find it t in any of the attributes to get it into Home Assistant.
Any ideas?

**Comment by kurim** [comment]
Hi martynhr,
check this: https://github.com/flobz/psa_car_controller/issues/667
Otherwise you can use node-red to expose those as switches and values
NodeRed:
![image](https://github.com/flobz/psa_car_controller/assets/1880220/63be1707-9063-4b18-9e66-0cdf769ef8fe)

Batteriegesudnheit is Battery SOH, with an function to make sure that the value is stored due the PSA API don't provide it all the time.

**Comment by Slin-nilS** [comment]
Hey @martynhr 
Add in Homeassistant config filge this Sensor:
```yaml
# Opel Corsa
- platform: rest
  name: opel_corsa
  resource: http://homeassistant.local:5000/get_vehicleinfo/YOURVIN?from_cache=1
  scan_interval: 60
  timeout: 30
  value_template: "OK"
  json_attributes:
    - energy
    - ...
- platform: template
  sensors:
    corsa_battery_voltage:
      friendly_name: "Battery Voltage"
      unit_of_measurement: "V"
      value_template: '{{ states.sensor.opel_corsa.attributes["battery"]["voltage"] * 4 }}'
 ```
 
![image](https://github.com/flobz/psa_car_controller/assets/95978369/69e5abe2-efec-4437-8f79-035ab61fd592)

**Reply by Slin-nilS** [reply]
@martynhr sorry, I had misread. You want the SOH and not the SOC

**Comment by zazazouthecat** [comment]
Exemple for sensor SOH (add in sensor.yaml file)

```
# peugeot_e208 soh_control
- platform: rest
  name: peugeot_e208_soh_control
  resource: http://YourIPServer:5000/battery/soh/YourVin
  scan_interval: 60
  timeout: 300
  value_template: 'OK'
  json_attributes:
   - soh
- platform: template
  sensors:
    e208_battery_soh:
      friendly_name: "Battery SOH"
	  unit_of_measurement: "%"
      value_template: "{{ state_attr('sensor.peugeot_e208_battery_soh', 'soh') }}"
      icon_template: mdi:battery-heart-variant

```
