### DISCUSSION TITLE
device_tracker for HA ?

### DISCUSSION THREAD

**Discussion by bmerciergallay** [flobz/psa_car_controller#799] [Q&A]
has anyone configured a device_tracker based on the PSACC to get the location in HA and being able to base automations on the car location ?
Any help please ?

**Comment by grahamrjuk** [comment]
I have a device tracker working:

The automation is:
```
alias: "Corsa E: Update position"
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.corsa_e_longitude
      - sensor.corsa_e_latitude
condition: []
action:
  - service: device_tracker.see
    data:
      mac: FF:FF:FF:FF:FF:F7
      dev_id: corsa_e
      source_type: gps
      host_name: corsa_e
      location_name: Corsa E location
      gps:
        - "{{ states('sensor.corsa_e_longitude') | float }}"
        - "{{ states('sensor.corsa_e_latitude') | float }}"
      gps_accuracy: 20
      battery: "{{ states('sensor.corsa_e_battery_level') | round(0) }}"
mode: single
```

and I have separated the position in to separate longitude and latitude, along with other config for psacc in sensors.yaml.
In `platform: rest`
```
  json_attributes:
    - last_position
```

In `platform: template`
```
    corsa_e_latitude
      friendly_name: "Corsa E latitude"                                                                                                                                                                                                                                                                                                                                                              
      value_template: "{{ state_attr('sensor.vauxhall_corsa_e', 'last_position')['geometry']['coordinates'][0] }}"                                                                                                                                                                                                                                                                                   
      unique_id: corsa_e_latitude                                                                                                                                                                                                                                                                                                                                                                    
    corsa_e_longitude:                                                                                                                                                                                                                                                                                                                                                                               
      friendly_name: "Corsa E longitude"                                                                                                                                                                                                                                                                                                                                                             
      value_template: "{{ state_attr('sensor.vauxhall_corsa_e', 'last_position')['geometry']['coordinates'][1] }}"                                                                                                                                                                                                                                                                                   
      unique_id: corsa_e_longitude                                                                                                                                                                                                                                                                                                                                                                   
```

Obviously, I hope, change corsa_e for your chosen reference.

I haven't tried any automations based on this, and I haven't tried to get a geocoded version either.
