### ISSUE TITLE
Fatal Python error: init_interp_main: can't initialize time

### ISSUE THREAD

**Issue by S474N** [flobz/psa_car_controller#380]
After up in log:

```
pi@RaspiServer:~ $ docker logs psacc
Containerised psa_car_controller loading...
Fatal Python error: init_interp_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted

Current thread 0xb6f61520 (most recent call first):
<no Python frame>
Containerised psa_car_controller loading...
Fatal Python error: init_interp_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted

Current thread 0xb6fee520 (most recent call first):
<no Python frame>
```

Definition in docker-compose.yml:
  ```
psacc:
    container_name: psacc
    image: flobz/psa_car_controller:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./volumes/psacarcontroller/config:/config
```

RPi 4B, 32bit raspbian, 2GB RAM
docker-compose version 2.6.0
