### ISSUE TITLE
Get info if delayed time charge activated and deactivate it

### ISSUE THREAD

**Issue by Matssa56** [flobz/psa_car_controller#546]
Hi,

I'm doing some automations under Home Assistant to automatically activate the delayed time in order to charge my car at 2am.

When getting the vehicle status, we can get the delayed time that is sent to the car (energy --> charging time --> next_delayed_time).
However, we don't have any value saying that it is activated or not (at least not in the get vehicle information). Therefore I can't check if my command is correctly sent and used by my car or not.

When checking the application logs, apparently we can manage to get this information :

2023-05-04 22:42:17,781 :: INFO :: veh_charge_request: topic: psa/RemoteServices/from/cid/OV-ACNTXXXXXX/VehCharge: {'program': {'hour': '2', 'minute': '0'}, 'type': 'delayed'}

How can we get this info in a sensor for Home Assistant? Is there a way to get this json value, maybe another link that we can ping? Currently I get the information from the two following links : 
http://localhost:5000/get_vehicleinfo/VIN?from_cache=1
http://localhost:5000/charge_control?vin=VIN&?always_check=true

Another thing, is there a way to send a command to disable the delayed hour?

I checked the API ddocumentation and I didn't manage to find anything, maybe I need to check the fleet API?

Thanks!

**Comment by Ilpo55** [comment]
I use this. (Edit and test the value_template code in Template editor). 

My rest sensor:

```
sensor:
  - platform: rest
    name: peugeot_e3008
    resource: http://b9f12d83-psacc:5000/get_vehicleinfo/VF3M45GBUxxxxxxxx?from_cache=1
    scan_interval: 60
    timeout: 30
    value_template: 'OK'
    json_attributes:
     - energy
     - timed_odometer
     - battery
     - preconditionning
```

My value_template for the time in the car.:

```
      e3008_lataus_ajastusaika:
        friendly_name: "Latauksen ajastusaika"
        value_template: >-
          {% set la = states.sensor.peugeot_e3008.attributes["energy"][0]["charging"]["next_delayed_time"] %}
          {% set la = la | replace("PT","") | replace("H",",") | replace("M",",") | replace("S",",") %}
          {% set h = la.split(",")[0] %}
          {% set m = la.split(",")[1] %}
          {% if (h | length) == 1 %}
          {% set h = "0"+h %}
          {% endif %}
          {% if (m | length) == 1 %}
          {% set m = "0"+m %}
          {% elif (m | length) == 0 %}
          {% set m = "00" %}
          {% endif %}
          {{h}}:{{m}}
```

**Comment by Matssa56** [comment]
> I use this.
> 
> My rest sensor:
> 
> ```
> sensor:
>   - platform: rest
>     name: peugeot_e3008
>     resource: http://b9f12dxx-psacc:5000/get_vehicleinfo/VF3M45GBUxxxxxxxx?from_cache=1
>     scan_interval: 60
>     timeout: 30
>     value_template: 'OK'
>     json_attributes:
>      - energy
>      - timed_odometer
>      - battery
>      - preconditionning
> ```
> 
> My value_template for the time in the car.:
> 
> ```
>       e3008_lataus_ajastusaika:
>         friendly_name: "Latauksen ajastusaika"
>         value_template: >-
>           {% set la = states.sensor.peugeot_e3008.attributes["energy"][0]["charging"]["next_delayed_time"] %}
>           {% set la = la | replace("PT","") | replace("H",",") | replace("M",",") | replace("S",",") %}
>           {% set h = la.split(",")[0] %}
>           {% set m = la.split(",")[1] %}
>           {% if (h | length) == 1 %}
>           {% set h = "0"+h %}
>           {% endif %}
>           {% if (m | length) == 1 %}
>           {% set m = "0"+m %}
>           {% elif (m | length) == 0 %}
>           {% set m = "00" %}
>           {% endif %}
>           {{h}}:{{m}}
> ```
> 
> (Edit and test the value_template code in Template editor).

Thanks for your feedback, the issue is that the value is set in the sensor isn't activated 

If I check the Opel app on my phone, the delayed time is correctly set l, however it isn't activated. And in the Opel car sensor, there isn't any value to see if the delayed charge it set or not.

**Comment by Ilpo55** [comment]
I use these commands to put the car into immediate charge (lataus_on:) / delayed charge (lataus_off:) :

```
rest_command:
  e3008_lataus_on:
    url: "http://b9f12dxx-psacc:5000/charge_now/VF3M45GBUxxxxxxxx/1"
    method: GET
  e3008_lataus_off:
    url: "http://b9f12dxx-psacc:5000/charge_now/VF3M45GBUxxxxxxxx/0"
    method: GET
```
