### ISSUE TITLE
Home assistant entity for state of health 

### ISSUE THREAD

**Issue by atze09** [flobz/psa_car_controller#667]
Hey guys,
This is not a big, but I need your best practice. Sorry for using this bug report 

I just saw that the home assistant addon now displays the state of health.
Does anyone already created an entity in home assistant for that.
I am struggling with doing so.
Hope anyone can help me.
Thanks.
Best regards,
Dominik

**Comment by kurim** [comment]
If you use nodered to create sensors just add this:

![image](https://github.com/flobz/psa_car_controller/assets/1880220/ee43856d-2629-4f49-82b8-fa936a4945e4)

If you like i can provide you my full example.

**Comment by atze09** [comment]
> If you use nodered to create sensors just add this:
> 
> ![image](https://user-images.githubusercontent.com/1880220/283508394-ee43856d-2629-4f49-82b8-fa936a4945e4.png)
> 
> If you like i can provide you my full example.

Thank you very much, i am not using NodeRed.
But i tried to get the data out of the JSON template but here i have no data under Energy.Battery:
![image](https://github.com/flobz/psa_car_controller/assets/6229866/4b3ded24-5c93-491b-87a4-8eff01df7051)

Do you have the data available when you query it from:
2.1 Get the car state :
http://localhost:5000/get_vehicleinfo/YOURVIN
?

**Comment by kurim** [comment]
Yes, but not always.
Mostly it show up if you call the update through the app.

**Comment by sod75** [comment]
have you tried getting the values from the cache ?
http://localhost:5000/get_vehicleinfo/YOURVIN?from_cache=1 not sure if this helps.

I have the following in my sensors.yaml to create sensors.

```
`  - platform: rest
    name: peugeot_3008
    resource: http://192.168.0.91:3000/get_vehicleinfo/VINXXXXXX?from_cache=1
    scan_interval: 60
    timeout: 30
    value_template: 'OK'
    json_attributes:
     - energy
     - timed_odometer
     - battery
     - environment
     - last_position
  - platform: template
    sensors:
      3008_battery_voltage:
        friendly_name: "Battery Voltage"
        unit_of_measurement: "V"
        value_template: '{{ states.sensor.peugeot_3008.attributes["battery"]["voltage"] * 4 }}'
      3008_battery_level:
        friendly_name: "Battery"
        unit_of_measurement: "%"
        value_template: '{{ states.sensor.peugeot_3008.attributes["energy"][0]["level"] }}'
```
`
Also I see  battery entry under energy, 
and a separate Battery stanza...

![image](https://github.com/flobz/psa_car_controller/assets/4673458/064db104-6734-4758-b11e-d4c9a21626f2)
