### ISSUE TITLE
Display Map

### ISSUE THREAD

**Issue by SabatoArdolino** [flobz/psa_car_controller#715]
**Describe the bug**
In my installation I can see Trip and Charge history but maps is wrong seems that only start and stop position was recorded. 
![2023-12-26_073424](https://github.com/flobz/psa_car_controller/assets/137244513/a809ed21-958e-476f-8de0-e2ce81591e15)

**Environment (please complete the following information):**
 - OS: Linux 
 - Opel Grandland Hybrid

**Comment by FEmser** [comment]
I can confirm this behavior. It seems that my car (Peugeot e208) will only send location updates after the ignition was turned of.
I already wondered if this is supposed to be like it or if this can be fixed somehow since the car does know its location also during driving.
Oh and also this messes up the the data whenever the end of a trip is in a underground garage and the connection is lost so no update will be sent.

**Comment by FilipeOS** [comment]
I can't replicate this, for me is working fine but I get log errors:

`Template variable warning: 'None' has no attribute 'moving' when rendering '{{ state_attr('sensor.psa', 'kinetic').moving }}'`

```
      - name: PSA Position
        unique_id: psa_position
        state: >-
          {{ state_attr('sensor.psa', 'kinetic').moving }}
        device_class: moving
        attributes:
          latitude: "{{ state_attr('sensor.psa', 'last_position').geometry.coordinates[1] }}"
          longitude: "{{ state_attr('sensor.psa', 'last_position').geometry.coordinates[0] }}"
```

`"kinetic": {"acceleration": 0.0, "moving": false, "pace": null, "speed": 0.0}`
