### ISSUE TITLE
Car model there, but not in abrp ref, what can I do?

### ISSUE THREAD

**Issue by Str00pwafel** [flobz/psa_car_controller#774]
Hi there,

New here and new car, please be patient with me :D 

The app gives me the error `ValueError: No vehicle in your account is compatible with this API, you vehicle is probably too old...`
However, the car is in the `car_models.yml` with the good VIN regex.
```
- !CarModel
  name: '208'
  battery_power: 0
  fuel_capacity: 44
  abrp_name:
  reg: VR3UPHN[SEK].*`
  ```
 My VIN begins with `VR3UPHNEKP`

However, in the `abrp ref` [here](https://api.iternio.com/1/tlm/get_carmodels_list?api_key=32b2162f-9599-4647-8139-66e9f9528370)
The model is not there(yet?). I have a new facelift Peugeot 208 GT (2024) non electric.

Is there a way so I can make this work now? Or do I need to wait for something, sorry if I'm misunderstanding this all.

Thank you in advance.
